[package]
org = "ballerina"
name = "jballerina.java.arrays"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/jballerina.java.arrays-test-utils-@project.version@.jar"
groupId = "io.ballerina.stdlib.jballerina.java.arrays.testutils"
artifactId = "jballerina.java.arrays-test-utils"
version = "@project.version@"
scope = "testOnly"
