[package]
org = "ballerina"
name = "jballerina.java.arrays"
version = "1.4.0"
authors = ["Ballerina"]
keywords = ["java", "arrays"]
repository = "https://github.com/ballerina-platform/module-ballerina-jballerina.java.arrays"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../test-utils/build/libs/jballerina.java.arrays-test-utils-1.4.0-SNAPSHOT.jar"
version = "1.4.0-SNAPSHOT"
scope = "testOnly"
