[package]
org = "ballerina"
name = "jballerina.java.arrays"
version = "1.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/jballerina.java.arrays-test-utils-1.0.0-SNAPSHOT.jar"
version = "1.0.0-SNAPSHOT"
scope = "testOnly"
