[package]
org = "ballerina"
name = "jballerina.java.arrays"
version = "1.1.0"
authors = ["Ballerina"]
keywords = ["java", "arrays"]
repository = "https://github.com/ballerina-platform/module-ballerina-jballerina.java.arrays"
license = ["Apache-2.0"]
distribution = "slbeta6"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/jballerina.java.arrays-test-utils-1.1.0.jar"
version = "1.1.0"
scope = "testOnly"
